"""
Ticker → company logo URL mapping.

Uses logo.clearbit.com (free, no auth) with company domain lookups.
Falls back gracefully — returns None for unknown tickers.
"""

# Ticker → company website domain
# Hand-patched entries for tickers yfinance couldn't resolve (international,
# acquired-but-still-trading, or low-coverage names). Keep alphabetical so
# build_logo_domains.py merges cleanly on re-run.
_MANUAL_DOMAINS: dict[str, str] = {
    "300347 / 3347": "tigermedgrp.com",
    "4581":          "taisho.co.jp",
    "COLO B":        "coloplast.com",
    "GLB":           "glanbia.com",
    "INDEGENE":      "indegene.com",
    "KRKG":          "krka.biz",
    "LUN":           "lundbeck.com",
    "MRK GR":        "merckgroup.com",
    "PDCO":          "pattersoncompanies.com",
    "SRDX":          "surmodics.com",
    "SUVENPHAR":     "suven.com",
    "SXS":           "spectris.com",
    "VERV":          "vervetx.com",
}

_TICKER_DOMAINS: dict[str, str] = {
    '000710'      : 'berrygenomics.com',
    '002821'      : 'asymchem.com.cn',
    '207940'      : 'samsungbiologics.com',
    '2269'        : 'wuxibiologics.com',
    '2359'        : 'wuxiapptec.com',
    '300760'      : 'mindray.com',
    '3759'        : 'pharmaron.com',
    '4151'        : 'kyowakirin.com',
    '4503'        : 'astellas.com',
    '4519'        : 'chugai-pharm.co.jp',
    '4523'        : 'eisai.co.jp',
    '4527'        : 'rohto.co.jp',
    '4568'        : 'daiichisankyo.com',
    '4578'        : 'otsuka.com',
    '4901'        : 'holdings.fujifilm.com',
    '4967'        : 'kobayashi.co.jp',
    '6185'        : 'cansinotech.com',
    '7733'        : 'olympus.co.jp',
    '7751'        : 'global.canon',
    '8086'        : 'nipro.co.jp',
    'A'           : 'agilent.com',
    'ABBV'        : 'abbvie.com',
    'ABT'         : 'abbott.com',
    'ACAD'        : 'acadia.com',
    'ADMA'        : 'admabiologics.com',
    'ADPT'        : 'adaptivebiotech.com',
    'AFX'         : 'zeiss.com',
    'AGL'         : 'agilonhealth.com',
    'ALGN'        : 'aligntech.com',
    'ALM'         : 'almirall.com',
    'ALNY'        : 'alnylam.com',
    'AMGN'        : 'amgen.com',
    'AMRX'        : 'amneal.com',
    'AMWL'        : 'business.amwell.com',
    'ANAB'        : 'anaptysbio.com',
    'ANGO'        : 'angiodynamics.com',
    'ANIP'        : 'anipharmaceuticals.com',
    'APGE'        : 'apogeetherapeutics.com',
    'ARGX'        : 'argenx.com',
    'ARVN'        : 'arvinas.com',
    'ASND'        : 'ascendispharma.com',
    'ASTH'        : 'astranahealth.com',
    'ATEC'        : 'atecspine.com',
    'ATRC'        : 'atricure.com',
    'AUROPHARMA'  : 'aurobindo.com',
    'AVTR'        : 'avantorsciences.com',
    'AXSM'        : 'axsome.com',
    'AZN'         : 'astrazeneca.com',
    'AZTA'        : 'azenta.com',
    'BANB'        : 'bachem.com',
    'BAVA'        : 'bavarian-nordic.com',
    'BAX'         : 'baxter.com',
    'BAYN'        : 'bayer.com',
    'BDX'         : 'bd.com',
    'BEAM'        : 'beamtx.com',
    'BHC'         : 'bauschhealth.com',
    'BIIB'        : 'biogen.com',
    'BIM'         : 'biomerieux.com',
    'BIO'         : 'bio-rad.com',
    'BIO3'        : 'biotest.com',
    'BIOCON'      : 'biocon.com',
    'BLCO'        : 'bausch.com',
    'BMRN'        : 'biomarin.com',
    'BMY'         : 'bms.com',
    'BNTX'        : 'biontech.de',
    'BRBR'        : 'bellring.com',
    'BRKR'        : 'bruker.com',
    'BSX'         : 'bostonscientific.com',
    'BTSG'        : 'brightspringhealth.com',
    'CAH'         : 'cardinalhealth.com',
    'CDNA'        : 'caredx.com',
    'CDXS'        : 'codexis.com',
    'CERT'        : 'certara.com',
    'CHD'         : 'churchdwight.com',
    'CIPLA'       : 'cipla.com',
    'COGT'        : 'cogentbio.com',
    'COLL'        : 'collegiumpharma.com',
    'COO'         : 'coopercos.com',
    'COR'         : 'cencora.com',
    'CORT'        : 'corcept.com',
    'CPRX'        : 'catalystpharma.com',
    'CRL'         : 'criver.com',
    'CRNX'        : 'crinetics.com',
    'CRSP'        : 'crisprtx.com',
    'CSL'         : 'csl.com',
    'CSTL'        : 'castlebiosciences.com',
    'CTEC'        : 'convatecgroup.com',
    'CTEV'        : 'claritev.com',
    'CTKB'        : 'cytekbio.com',
    'CVSG'        : 'cvsukltd.co.uk',
    'CYTK'        : 'cytokinetics.com',
    'DAWN'        : 'dayonebio.com',
    'DGX'         : 'questdiagnostics.com',
    'DH'          : 'definitivehc.com',
    'DHR'         : 'danaher.com',
    'DIA'         : 'int.diasorin.com',
    'DIM'         : 'sartorius.com',
    'DIVISLAB'    : 'divislabs.com',
    'DOCS'        : 'doximity.com',
    'DXCM'        : 'dexcom.com',
    'EBS'         : 'emergentbiosolutions.com',
    'EDIT'        : 'editasmedicine.com',
    'EL'          : 'essilorluxottica.com',
    'ELAN'        : 'elanco.com',
    'EMBC'        : 'embecta.com',
    'ENTG'        : 'entegris.com',
    'ERF'         : 'eurofins.com',
    'ESTA'        : 'establishmentlabs.com',
    'EVH'         : 'evolent.com',
    'EVT'         : 'funds.eatonvance.com',
    'EW'          : 'edwards.com',
    'EWTX'        : 'edgewisetx.com',
    'EXEL'        : 'exelixis.com',
    'FLGT'        : 'fulgentgenetics.com',
    'FRPT'        : 'freshpet.com',
    'FTRE'        : 'fortrea.com',
    'GALD'        : 'galderma.com',
    'GEHC'        : 'gehealthcare.com',
    'GH'          : 'guardanthealth.com',
    'GILD'        : 'gilead.com',
    'GKOS'        : 'glaukos.com',
    'GLENMARK'    : 'glenmarkpharma.com',
    'GMAB'        : 'genmab.com',
    'GMED'        : 'globusmedical.com',
    'GRFS'        : 'grifols.com',
    'GSK'         : 'gsk.com',
    'GXI'         : 'gerresheimer.com',
    'HAE'         : 'haemonetics.com',
    'HALO'        : 'halozyme.com',
    'HCAT'        : 'healthcatalyst.com',
    'HIK'         : 'hikma.com',
    'HIMS'        : 'hims.com',
    'HLF'         : 'herbalife.com',
    'HLMA'        : 'halma.com',
    'HLN'         : 'haleon.com',
    'HLS'         : 'healius.com.au',
    'HQY'         : 'healthequity.com',
    'HRMY'        : 'harmonybiosciences.com',
    'HSIC'        : 'henryschein.com',
    'HSTM'        : 'healthstream.com',
    'HYPE3'       : 'hypera.com.br',
    'IART'        : 'integralife.com',
    'ICLR'        : 'iconplc.com',
    'ICUI'        : 'icumed.com',
    'IDIA'        : 'idorsia.com',
    'IDOX'        : 'idoxgroup.com',
    'IDXX'        : 'idexx.com',
    'ILMN'        : 'illumina.com',
    'INCY'        : 'incyte.com',
    'INDV'        : 'indivior.com',
    'INGN'        : 'provider.inogen.com',
    'INMD'        : 'inmodemd.com',
    'INSM'        : 'insmed.com',
    'INSP'        : 'inspiresleep.com',
    'IONS'        : 'ionis.com',
    'IOVA'        : 'iovance.com',
    'IPN'         : 'ipsen.com',
    'IQV'         : 'iqvia.com',
    'IRTC'        : 'irhythmtech.com',
    'ISRG'        : 'intuitive.com',
    'ITGR'        : 'integer.net',
    'JAZZ'        : 'jazzpharma.com',
    'JNJ'         : 'jnj.com',
    'KRYS'        : 'krystalbio.com',
    'KVUE'        : 'kenvue.com',
    'LAB'         : 'standardbio.com',
    'LEGN'        : 'legendbiotech.com',
    'LFST'        : 'lifestance.com',
    'LGND'        : 'ligand.com',
    'LH'          : 'labcorp.com',
    'LIVN'        : 'livanova.com',
    'LLY'         : 'lilly.com',
    'LNTH'        : 'lantheus.com',
    'LONN'        : 'lonza.com',
    'LUPIN'       : 'lupin.com',
    'MCK'         : 'mckesson.com',
    'MD'          : 'pediatrix.com',
    'MDGL'        : 'madrigalpharma.com',
    'MDT'         : 'medtronic.com',
    'MED'         : 'medifastinc.com',
    'MEDP'        : 'medpace.com',
    'MLYS'        : 'mineralystx.com',
    'MMSI'        : 'merit.com',
    'MRK'         : 'merck.com',
    'MRNA'        : 'modernatx.com',
    'MRVI'        : 'maravai.com',
    'MTD'         : 'mt.com',
    'MYGN'        : 'myriad.com',
    'NATR'        : 'naturessunshine.com',
    'NBIX'        : 'neurocrine.com',
    'NEO'         : 'neogenomics.com',
    'NMRA'        : 'neumoratx.com',
    'NTLA'        : 'intelliatx.com',
    'NTRA'        : 'natera.com',
    'NUS'         : 'nuskin.com',
    'NUVB'        : 'nuvationbio.com',
    'NVAX'        : 'novavax.com',
    'NVO'         : 'novonordisk.com',
    'NVS'         : 'novartis.com',
    'NVST'        : 'envistaco.com',
    'OGN'         : 'organon.com',
    'OM'          : 'outsetmedical.com',
    'ONC'         : 'beonemedicines.com',
    'OPCH'        : 'optioncarehealth.com',
    'ORCL'        : 'oracle.com',
    'ORNBV'       : 'orionpharma.com',
    'OSUR'        : 'orasure.com',
    'PACB'        : 'pacb.com',
    'PAHC'        : 'pahc.com',
    'PBH'         : 'prestigebrands.com',
    'PCRX'        : 'pacira.com',
    'PETS'        : 'petsathomeplc.com',
    'PFE'         : 'pfizer.com',
    'PG'          : 'pginvestor.com',
    'PHIA'        : 'philips.com',
    'PHR'         : 'phreesia.com',
    'PINC'        : 'premierinc.com',
    'PLRX'        : 'pliantrx.com',
    'PME'         : 'promed.com.au',
    'PODD'        : 'insulet.com',
    'PPLPHARMA'   : 'piramalpharma.com',
    'PRAX'        : 'praxismedicines.com',
    'PRCT'        : 'procept-biorobotics.com',
    'PRGO'        : 'perrigo.com',
    'PRME'        : 'primemedicine.com',
    'PRVA'        : 'priviahealth.com',
    'PSNL'        : 'personalis.com',
    'PTCT'        : 'ptcbio.com',
    'QDEL'        : 'quidelortho.com',
    'QGEN'        : 'qiagen.com',
    'RARE'        : 'ultragenyx.com',
    'RCKT'        : 'rocketpharma.com',
    'RDY'         : 'drreddys.com',
    'REC'         : 'recordati.com',
    'REGN'        : 'regeneron.com',
    'REPL'        : 'replimune.com',
    'RGEN'        : 'repligen.com',
    'RKT'         : 'reckitt.com',
    'RMD'         : 'resmed.com',
    'ROG'         : 'roche.com',
    'RPRX'        : 'royaltypharma.com',
    'RVTY'        : 'revvity.com',
    'RXRX'        : 'recursion.com',
    'SDGR'        : 'schrodinger.com',
    'SDZ'         : 'sandoz.com',
    'SFZN'        : 'siegfried.ch',
    'SGMO'        : 'sangamo.com',
    'SHL'         : 'sonichealthcare.com',
    'SIBN'        : 'si-bone.com',
    'SLNO'        : 'soleno.life',
    'SLP'         : 'simulations-plus.com',
    'SLQT'        : 'selectquote.com',
    'SMPL'        : 'thesimplygoodfoodscompany.com',
    'SN'          : 'smith-nephew.com',
    'SNY'         : 'sanofi.com',
    'SOLV'        : 'solventum.com',
    'SRPT'        : 'sarepta.com',
    'SRT'         : 'sartorius.com',
    'STMN'        : 'straumann.com',
    'STOK'        : 'stoketherapeutics.com',
    'STVN'        : 'stevanatogroup.com',
    'SUNPHARMA'   : 'sunpharma.com',
    'SUPN'        : 'supernus.com',
    'SYK'         : 'stryker.com',
    'SYNGENE'     : 'syngeneintl.com',
    'TAK'         : 'takeda.com',
    'TCMD'        : 'tactilemedical.com',
    'TDOC'        : 'teladochealth.com',
    'TECH'        : 'bio-techne.com',
    'TECN'        : 'tecan.com',
    'TEM'         : 'tempus.com',
    'TEVA'        : 'tevapharm.com',
    'TFX'         : 'teleflex.com',
    'TMDX'        : 'transmedics.com',
    'TMO'         : 'thermofisher.com',
    'TNDM'        : 'tandemdiabetes.com',
    'TORNTPHARM'  : 'torrentpharma.com',
    'TRUP'        : 'trupanion.com',
    'TVTX'        : 'travere.com',
    'TWST'        : 'twistbioscience.com',
    'TXG'         : '10xgenomics.com',
    'UCB'         : 'ucb.com',
    'USNA'        : 'usana.com',
    'UTHR'        : 'unither.com',
    'VALN'        : 'valneva.com',
    'VCYT'        : 'veracyte.com',
    'VEEV'        : 'veeva.com',
    'VETO'        : 'vetoquinol.com',
    'VIRP'        : 'corporate.virbac.com',
    'VNDA'        : 'vandapharma.com',
    'VREX'        : 'vareximaging.com',
    'VRTX'        : 'vrtx.com',
    'VTRS'        : 'viatris.com',
    'WAT'         : 'waters.com',
    'WAY'         : 'waystar.com',
    'WST'         : 'westpharma.com',
    'WVE'         : 'wavelifesciences.com',
    'XRAY'        : 'dentsplysirona.com',
    'ZBH'         : 'zimmerbiomet.com',
    'ZEAL'        : 'zealandpharma.com',
    'ZTS'         : 'zoetis.com',
    'ZYDUSLIFE'   : 'zyduslife.com',
}


def logo_url(ticker: str, size: int = 64) -> str | None:
    """Return a Google Favicon URL for a ticker, or None if unmapped.

    Google's favicon service has near-100% coverage and supports sizes
    up to 256.  We request 2× the display size for retina clarity.

    Lookup order: manual overrides → auto-generated map. Both keyed by
    upper-cased display ticker.
    """
    t = ticker.upper()
    domain = _MANUAL_DOMAINS.get(t) or _TICKER_DOMAINS.get(t)
    if not domain:
        return None
    return f"https://www.google.com/s2/favicons?domain={domain}&sz={size}"


def logo_img_tag(ticker: str, size: int = 20) -> str:
    """Return an <img> tag for inline use, or empty string if no logo."""
    url = logo_url(ticker, size=size * 2)  # 2x for retina
    if not url:
        return ""
    return (
        f'<img src="{url}" width="{size}" height="{size}" '
        f'style="border-radius:4px;vertical-align:middle;object-fit:contain;" '
        f'onerror="this.style.display=\'none\'" loading="lazy">'
    )
