"""
Ticker → company logo URL mapping.

Uses logo.clearbit.com (free, no auth) with company domain lookups.
Falls back gracefully — returns None for unknown tickers.
"""

# Ticker → company website domain
_TICKER_DOMAINS: dict[str, str] = {
    "ADBE":   "adobe.com",
    "ADP":    "adp.com",
    "ADSK":   "autodesk.com",
    "AGYS":   "agilysys.com",
    "AI":     "c3.ai",
    "AKAM":   "akamai.com",
    "ALFA":   "alfasystems.com",
    "ALKT":   "alkami.com",
    "ALRM":   "alarm.com",
    "AMA":    "amadeus.com",
    "AMPL":   "amplitude.com",
    "ANET":   "arista.com",
    "APP":    "applovin.com",
    "APPF":   "appfolio.com",
    "APPN":   "appian.com",
    "ASAN":   "asana.com",
    "ATEN":   "a10networks.com",
    "AVPT":   "avepoint.com",
    "AXON":   "axon.com",
    "BAND":   "bandwidth.com",
    "BB":     "blackberry.com",
    "BIGC":   "bigcommerce.com",
    "BILL":   "bill.com",
    "BL":     "blackline.com",
    "BLKB":   "blackbaud.com",
    "BLND":   "blend.com",
    "BOX":    "box.com",
    "BR":     "broadridge.com",
    "BRZE":   "braze.com",
    "BSY":    "bentley.com",
    "CCC":    "cccis.com",
    "CCSI":   "consensus.com",
    "CDNS":   "cadence.com",
    "CERT":   "certara.com",
    "CFLT":   "confluent.io",
    "CHKP":   "checkpoint.com",
    "CLBT":   "cellebrite.com",
    "COUR":   "coursera.org",
    "CRM":    "salesforce.com",
    "CRWD":   "crowdstrike.com",
    "CSU":    "csisoftware.com",
    "CTEV":   "claritev.com",
    "CVLT":   "commvault.com",
    "CWAN":   "clearwateranalytics.com",
    "CXM":    "sprinklr.com",
    "CYBR":   "cyberark.com",
    "DASSY":  "3ds.com",
    "DBD":    "dieboldnixdorf.com",
    "DBX":    "dropbox.com",
    "DCBO":   "docebo.com",
    "DDOG":   "datadoghq.com",
    "DOCN":   "digitalocean.com",
    "DOCS":   "doximity.com",
    "DOCU":   "docusign.com",
    "DOMO":   "domo.com",
    "DT":     "dynatrace.com",
    "DV":     "doubleverify.com",
    "EGAN":   "egain.com",
    "EGHT":   "8x8.com",
    "ESTC":   "elastic.co",
    "EVCM":   "evercommerce.com",
    "EXFY":   "expensify.com",
    "EXTR":   "extremenetworks.com",
    "FDS":    "factset.com",
    "FFIV":   "f5.com",
    "FICO":   "fico.com",
    "FIVN":   "five9.com",
    "FLYW":   "flywire.com",
    "FROG":   "jfrog.com",
    "FRSH":   "freshworks.com",
    "FSLY":   "fastly.com",
    "FTNT":   "fortinet.com",
    "GBG":    "gbgplc.com",
    "GDDY":   "godaddy.com",
    "GEN":    "gendigital.com",
    "GLBE":   "global-e.com",
    "GTLB":   "gitlab.com",
    "GWRE":   "guidewire.com",
    "HPE":    "hpe.com",
    "HQY":    "healthequity.com",
    "HUBS":   "hubspot.com",
    "IIIV":   "i3verticals.com",
    "INTA":   "intapp.com",
    "INTU":   "intuit.com",
    "IOT":    "samsara.com",
    "JAMF":   "jamf.com",
    "KARO":   "karooooo.com",
    "KLTR":   "kaltura.com",
    "KVYO":   "klaviyo.com",
    "KXS":    "kinaxis.com",
    "LSPD":   "lightspeedhq.com",
    "MANH":   "manh.com",
    "MDB":    "mongodb.com",
    "MNDY":   "monday.com",
    "NABL":   "n-able.com",
    "NAV":    "navan.com",
    "NCNO":   "ncino.com",
    "NEM":    "nemetschek.com",
    "NET":    "cloudflare.com",
    "NICE":   "nice.com",
    "NOW":    "servicenow.com",
    "NTAP":   "netapp.com",
    "NTCT":   "netscout.com",
    "NTNX":   "nutanix.com",
    "NTSK":   "netskope.com",
    "OKTA":   "okta.com",
    "OMDA":   "omadahealth.com",
    "ONTF":   "on24.com",
    "OS":     "onestream.com",
    "OSPN":   "onespan.com",
    "OTEX":   "opentext.com",
    "PANW":   "paloaltonetworks.com",
    "PATH":   "uipath.com",
    "PAY":    "paymentus.com",
    "PAYC":   "paycom.com",
    "PAYX":   "paychex.com",
    "PCOR":   "procore.com",
    "PCTY":   "paylocity.com",
    "PD":     "pagerduty.com",
    "PEGA":   "pega.com",
    "PHR":    "phreesia.com",
    "PLTR":   "palantir.com",
    "PRGS":   "progress.com",
    "PSTG":   "purestorage.com",
    "PTC":    "ptc.com",
    "QLYS":   "qualys.com",
    "QTWO":   "q2.com",
    "RAMP":   "liveramp.com",
    "RBRK":   "rubrik.com",
    "RDWR":   "radware.com",
    "RNG":    "ringcentral.com",
    "ROP":    "ropertech.com",
    "RPD":    "rapid7.com",
    "RSKD":   "riskified.com",
    "S":      "sentinelone.com",
    "SABR":   "sabre.com",
    "SAGE":   "sage.com",
    "SAIL":   "sailpoint.com",
    "SAP":    "sap.com",
    "SDR":    "siteminder.com",
    "SEMR":   "semrush.com",
    "SHOP":   "shopify.com",
    "SKIL":   "skillsoft.com",
    "SMWB":   "similarweb.com",
    "SNOW":   "snowflake.com",
    "SNPS":   "synopsys.com",
    "SPSC":   "spscommerce.com",
    "SPT":    "sproutsocial.com",
    "SRAD":   "sportradar.com",
    "SSNC":   "ssctech.com",
    "TDC":    "teradata.com",
    "TEAM":   "atlassian.com",
    "TEM":    "tempus.com",
    "TENB":   "tenable.com",
    "TMICY":  "trendmicro.com",
    "TMNS":   "temenos.com",
    "TMV":    "teamviewer.com",
    "TNET":   "trinet.com",
    "TOST":   "toasttab.com",
    "TRMB":   "trimble.com",
    "TTAN":   "servicetitan.com",
    "TTD":    "thetradedesk.com",
    "TWLO":   "twilio.com",
    "TYL":    "tylertech.com",
    "U":      "unity.com",
    "UDMY":   "udemy.com",
    "UPLD":   "uplandsoftware.com",
    "VEEV":   "veeva.com",
    "VERX":   "vertexinc.com",
    "VRNS":   "varonis.com",
    "VRNT":   "verint.com",
    "VRRM":   "verramobility.com",
    "VRSK":   "verisk.com",
    "VRSN":   "verisign.com",
    "VTEX":   "vtex.com",
    "WAY":    "waystar.com",
    "WDAY":   "workday.com",
    "WEAV":   "getweave.com",
    "WIX":    "wix.com",
    "WK":     "workiva.com",
    "WTC":    "wisetechglobal.com",
    "XRO":    "xero.com",
    "YEXT":   "yext.com",
    "YOU":    "clearme.com",
    "ZETA":   "zetaglobal.com",
    "ZI":     "zoominfo.com",
    "ZM":     "zoom.us",
    "ZS":     "zscaler.com",
}


def logo_url(ticker: str, size: int = 64) -> str | None:
    """Return a Google Favicon URL for a ticker, or None if unmapped.

    Google's favicon service has near-100% coverage and supports sizes
    up to 256.  We request 2× the display size for retina clarity.
    """
    domain = _TICKER_DOMAINS.get(ticker.upper())
    if not domain:
        return None
    return f"https://www.google.com/s2/favicons?domain={domain}&sz={size}"


def logo_img_tag(ticker: str, size: int = 20) -> str:
    """Return an <img> tag for inline use, or empty string if no logo."""
    url = logo_url(ticker, size=size * 2)  # 2x for retina
    if not url:
        return ""
    return (
        f'<img src="{url}" width="{size}" height="{size}" '
        f'style="border-radius:4px;vertical-align:middle;object-fit:contain;" '
        f'onerror="this.style.display=\'none\'" loading="lazy">'
    )
